name = "GasPowerModels"
uuid = "1fcaf345-95e3-5b8b-91d6-2145eb844b9d"
authors = ["Russell Bent"]
repo = "https://github.com/lanl-ansi/GasPowerModels.jl"
version = "0.4.0"

[deps]
GasModels = "5e113713-6c35-5477-b766-e1109486666f"
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
PowerModelsRestoration = "23adbb12-a187-11e9-26a2-eb4d4e6e68fb"

[compat]
GasModels = "~0.9"
InfrastructureModels = "~0.6"
JSON = "~0.21"
JuMP = "~0.21"
Memento = "~1.0, ~1.1"
PowerModelsRestoration = "~0.6"
julia = "^1"

[extras]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Cbc", "Juniper", "Ipopt", "Logging", "Test"]
